// <auto-generated />
using System;
using CashSaver.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CashSaver.Repositories.Migrations
{
    [DbContext(typeof(CashSaverContext))]
    [Migration("20230314000609_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CashSaver.Domain.Bill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bill", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("42ae4de0-1b65-42e8-b045-9d603891ec92"),
                            CreatedAt = new DateTime(2023, 3, 14, 0, 6, 9, 257, DateTimeKind.Utc).AddTicks(9177),
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 100.00m,
                            Title = "Teste 1"
                        },
                        new
                        {
                            Id = new Guid("1f8686b6-0cf6-44c3-a35e-c866f656f63f"),
                            CreatedAt = new DateTime(2023, 3, 14, 0, 6, 9, 257, DateTimeKind.Utc).AddTicks(9202),
                            Description = "Descrição 2",
                            ExpirationDate = new DateTime(2023, 5, 13, 21, 6, 9, 257, DateTimeKind.Local).AddTicks(9189),
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaidDate = new DateTime(2023, 3, 13, 21, 6, 9, 257, DateTimeKind.Local).AddTicks(9180),
                            Price = 100.00m,
                            Title = "Teste 2"
                        },
                        new
                        {
                            Id = new Guid("6ad9e8d5-e2af-42db-a507-85ae367d64e5"),
                            CreatedAt = new DateTime(2023, 3, 14, 0, 6, 9, 257, DateTimeKind.Utc).AddTicks(9204),
                            Description = "Descrição 3",
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaidDate = new DateTime(2023, 3, 13, 21, 6, 9, 257, DateTimeKind.Local).AddTicks(9202),
                            Price = 100.00m,
                            Title = "Teste 3"
                        },
                        new
                        {
                            Id = new Guid("1c71bbc2-f9fc-4988-b1c5-f51e081aad20"),
                            CreatedAt = new DateTime(2023, 3, 14, 0, 6, 9, 257, DateTimeKind.Utc).AddTicks(9205),
                            Description = "Descrição 4",
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 100.00m,
                            Title = "Teste 4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
